import{a as L,S as v,i as c}from"./assets/vendor-b0d10f48.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const d of o.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&n(d)}).observe(document,{childList:!0,subtree:!0});function a(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(e){if(e.ep)return;e.ep=!0;const o=a(e);fetch(e.href,o)}})();const b=L.create({baseURL:"https://pixabay.com/api/",params:{key:"44049437-ef12fae0346c4a67068c57c01",image_type:"photo",orientation:"horizontal",safesearch:!0}});async function y(t,r=1){return(await b.get("",{params:{q:t,page:r,per_page:15}})).data}function w(t){return`<li class="gallery-item">
    <a href="${t.largeImageURL}">
    <img src="${t.webformatURL}" alt="${t.tags}"/>
    <div class="wrapper">
    <div><h3>Likes</h3><p>${t.likes}</p></div>
    <div><h3>Views</h3><p>${t.views}</p></div>
    <div><h3>Comments</h3><p>${t.comments}</p></div>
    <div><h3>Downloads</h3><p>${t.downloads}</p></div>
    </div>
    </a>
  </li>`}function u(t){return t.map(w).join("")}const S=document.querySelector(".form"),h=document.querySelector(".gallery"),s=document.querySelector(".loader"),l=document.querySelector(".js-btn-load"),m=new v(".gallery a",{animationSpeed:200,animationSlide:!0,disableScroll:!1,history:!1,captionsData:"alt",captionDelay:250});let i=1,g=15,f="",p=0;l.style.display="none";S.addEventListener("submit",async t=>{t.preventDefault();const r=t.target.elements.word.value.trim();if(f=r,i=1,!r){c.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}s.classList.remove("hidden"),s.style.display="block",l.style.display="none";try{const a=await y(r,i);if(a.hits.length===0)c.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});else{p=a.totalHits;const n=u(a.hits);h.innerHTML=n,m.refresh(),p>=i*g&&(l.style.display="block")}s.classList.add("hidden"),s.style.display="none"}catch(a){console.error("Error searching images:",a.message),s.classList.add("hidden"),s.style.display="none"}});l.addEventListener("click",async t=>{i+=1,s.classList.remove("hidden"),p<=i*g&&(l.style.display="none",c.error({title:"Error",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),s.classList.add("hidden"),s.style.display="none");try{const r=await y(f,i);if(r.hits.length===0)c.error({title:"Error",message:"We're sorry, but you've reached the end of search results.",position:"topRight"});else{const a=u(r.hits);h.insertAdjacentHTML("beforeend",a),m.refresh();const e=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})}s.classList.add("hidden"),s.style.display="none"}catch(r){console.error("Error loading more images:",r.message),s.classList.add("hidden"),s.style.display="none"}});
//# sourceMappingURL=commonHelpers.js.map
