import{a as L,S as v,i as d}from"./assets/vendor-b0d10f48.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const p of o.addedNodes)p.tagName==="LINK"&&p.rel==="modulepreload"&&n(p)}).observe(document,{childList:!0,subtree:!0});function i(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(e){if(e.ep)return;e.ep=!0;const o=i(e);fetch(e.href,o)}})();const b=L.create({baseURL:"https://pixabay.com/api/",params:{key:"44049437-ef12fae0346c4a67068c57c01",image_type:"photo",orientation:"horizontal",safesearch:!0}});async function u(t,r=1){return(await b.get("",{params:{q:t,page:r,per_page:15}})).data}function w(t){return`<li class="gallery-item">
    <a href="${t.largeImageURL}">
    <img src="${t.webformatURL}" alt="${t.tags}"/>
    <div class="wrapper">
    <div><h3>Likes</h3><p>${t.likes}</p></div>
    <div><h3>Views</h3><p>${t.views}</p></div>
    <div><h3>Comments</h3><p>${t.comments}</p></div>
    <div><h3>Downloads</h3><p>${t.downloads}</p></div>
    </div>
    </a>
  </li>`}function h(t){return t.map(w).join("")}const S=document.querySelector(".form"),l=document.querySelector(".gallery"),s=document.querySelector(".loader"),c=document.querySelector(".js-btn-load"),m=new v(".gallery a",{animationSpeed:200,animationSlide:!0,disableScroll:!1,history:!1,captionsData:"alt",captionDelay:250});let a=1,g=15,f="",y=0;c.style.display="none";S.addEventListener("submit",async t=>{t.preventDefault();const r=t.target.elements.word.value.trim();if(f=r,a=1,l.innerHTML="",!r){l.innerHTML="",d.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}s.classList.remove("hidden"),s.style.display="block",c.style.display="none";try{const i=await u(r,a);if(i.hits.length===0)l.innerHTML="",d.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});else{y=i.totalHits;const n=h(i.hits);l.innerHTML=n,m.refresh(),y>=a*g&&(c.style.display="block")}s.classList.add("hidden"),s.style.display="none"}catch(i){console.error("Error searching images:",i.message),s.classList.add("hidden"),s.style.display="none"}});c.addEventListener("click",async t=>{a+=1,s.classList.remove("hidden"),y<=a*g&&(c.style.display="none",d.error({title:"Error",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),s.classList.add("hidden"),s.style.display="none");try{const r=await u(f,a);if(r.hits.length===0)d.error({title:"Error",message:"We're sorry, but you've reached the end of search results.",position:"topRight"});else{const i=h(r.hits);l.insertAdjacentHTML("beforeend",i),m.refresh();const e=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})}s.classList.add("hidden"),s.style.display="none"}catch(r){console.error("Error loading more images:",r.message),s.classList.add("hidden"),s.style.display="none"}});
//# sourceMappingURL=commonHelpers.js.map
